import type { Metadata } from "next";
import "./globals.css";
import { roboto } from "./assets/fonts";

export const metadata: Metadata = {
   title: "Home",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={roboto.className}>
            {children}
         </body>
      </html>
   );
}
