import type { Metadata } from "next";
import "./styles/globals.css";
import { roboto } from "./assets/fonts";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import CTAsubscribeSection from "./components/CTAsubscribeSection/CTAsubscribeSection";

export const metadata: Metadata = {
   title: "Home",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={roboto.className}>
            <Header />
            {children}
            <CTAsubscribeSection />
            <Footer />
         </body>
      </html>
   );
}
