import type { Metadata } from "next";
import "./styles/globals.css";
import { roboto } from "./assets/fonts";
import Footer from "./components/Footer/Footer";
import CTAsubscribeSection from "./components/CTAsubscribeSection/CTAsubscribeSection";
import Header from "./components/Header/Header";
import { Analytics } from "@vercel/analytics/next";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
   title: "Home",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`bg-background ${roboto.className}`}>
            <StoreProvider>
               <Header />
               {children}
               <Analytics />
               <CTAsubscribeSection />
               <Footer />
            </StoreProvider>
         </body>
      </html>
   );
}
